### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by florian-rabe** [florian-rabe/Teaching#11]
Tutorials will start next week.

**Comment by florian-rabe** [comment]
Unless agreed otherwise, the tutorial will be held on Tuesdays at 8:15 in the same room as the lecture.

TAs and students may agree to have the tutorial in a different place or at a different time.
You can self-organize that without my involvement.

Your TAs are @rdeliallisi, @JHalili, and @orxhelili

**Comment by latticepolys** [comment]
Has there been any agreement as to when the tutorials will happen?

**Comment by rdeliallisi** [comment]
This week the tutorial will happen on Tuesday at 8:15. After Tuesday's tutorial I will send a doodle around so that you can select your preferred slots. I want to get some feedback in tomorrows tutorial about some of your preferred slots.
