### ISSUE TITLE
AaDS Final Exam

### ISSUE THREAD

**Issue by ShabbarRazaPk94** [florian-rabe/Teaching#115]
Hi, could you please give us an idea on how the final exam might look like?

Specifically, I am interested in knowing if we will be required to write some code in the exam.

**Comment by gcakir** [comment]
Hi Shabbar,

Professor told us in the last session of the classes that he would upload all the quizzes so that we can have an idea of how final exam could be. He also told us that there could be some programming/implementation questions in the final exam.

**Comment by ShabbarRazaPk94** [comment]
Hi, are there any topics that are covered in the lecture notes but are not relevant for the final exam?

**Comment by florian-rabe** [comment]
Topics not covered in the lectures or homeworks are much less relevant.

**Comment by ShabbarRazaPk94** [comment]
Hi, are we allowed to bring a cheat sheet for the AaDS final exam?

**Comment by florian-rabe** [comment]
No cheat sheet.
