### ISSUE TITLE
Homework policy

### ISSUE THREAD

**Issue by florian-rabe** [florian-rabe/Teaching#12]
Homeworks will usually be
* posted on Tuesday (in the github repository)
* due on Thursday morning (11:00) of the following week

Homeworks will be submitted via grader by uploading one zip file for each problem.

For each student, the weakest two homeworks are not counted for grading.
In exchange, there will be no deadline extensions whatsoever.
If you are officially excused for the majority of the week, the homework will not count for you.

**Comment by funkytori** [comment]
What is the grading policy on the actual homework?
i.e. how much do we get penalized for missing edge cases / errors / bad coding style etc... ?

**Comment by florian-rabe** [comment]
There are two main criteria
* obvious correctness: It should be as easy as possible for the TA to understand that your code is correct, e.g.,
  * no coding tricks (e.g., pointer arithmetic) - use an extra line if it makes the code easier to read
  * no optimization if it harms readability
  * document as necessary to enhance readability (in particular document any use of a library function that the TA might not know)
  * coding style does not matter unless it harms readability
  * comment loops with loop invariant and termination ordering
* efficiency, e.g.,
  * don't unnecessarily do something twice
  * don't drop out of the intended complexity class

Some of the above are things that we will learn in the lecture: loop invariant, termination ordering, complexity class.
Those of course only apply once we have learned them.

@rdeliallisi @JHalili @orxhelili
