### ISSUE TITLE
SaDS makeup exam

### ISSUE THREAD

**Issue by florian-rabe** [florian-rabe/Teaching#120]
Some of you were excused for the final exam.

I expect all of you to contact me on the first day on which you are not excused.
Once everybody is available, there will be a written make-up exam.

Typically this is difficult to schedule because students have other finals or leave campus.
Because you may be off-campus next semester, it can be even harder.

Respond to this thread with your scheduling constraints.

**Comment by Temirlan97** [comment]
Hello,
I have my last 2 finals on Friday (26th of June) from 9:00 to 14:30. And I'm leaving the campus on 3rd of June and will be off-campus next semester.

I can write the makeup on any time until June 3rd, except the above stated time of my last exams.

It would be really good to know about make-up time at least 24 hours before the exam, because I have some document work and might be off-campus for that.

Best regards,
Temirlan Ulugbek uulu

**Comment by KamilaHasanbega** [comment]
Same situation as Temirlan, other than leaving on Saturday 27th. First part of Saturday 27th, could work for me. Depending on when/if  the make up would be in September, I could possibly be able to attend it, although I wouldn't be on campus.

**Comment by jifanghang** [comment]
I'm Leaving on June the first and I don't have any more exams after friday (26th) so any time in between would be fine. And September also works for me.

**Comment by zhaoliu1996** [comment]
Same situation with Kamila, saturday morning would be perfect.

**Comment by florian-rabe** [comment]
I've spoken with the registrar now.

Unfortunately they're behind schedule in processing your excuses.
I will only find out later today who was officially excused and when they are not-excused anymore.
However, time is running out to conduct the make-up.

So I'm tentatively scheduling the make-up exam for tomorrow, Tuesday 09:00-11:00, IRC conference hall.
I will get back to you later today with details about who can attend.

If you are already off-campus until next year (like Kamila), the registrar recommended and allowed me to leave your grades incomplete until you are back on-campus.
Thus, you would have a make-up exam in January/February.

**Comment by florian-rabe** [comment]
I have not received all excuses yet.
Also, one student wants to do a reassessment. It is my understanding that this is not possible, but I have not received a definite ruling on this issue either.

To simplify the scheduling, I will go ahead with the **make-up exam tomorrow morning**.

**If you are excused, you must attend tomorrow.**

But even if you attend, I will only consider your exam if I eventually determine that you were eligible for a make-up or reassessment, respectively.
