### ISSUE TITLE
AaDS: Not registered on Jgrader

### ISSUE THREAD

**Issue by ruicao-github** [florian-rabe/Teaching#20]
Dear Dr. Rabe,

I am registered on Campusnet for AaDS but could not select AaDS as active course and submit homework on Jgrader.

Best,

Rui Cao

**Comment by MelvinWolf** [comment]
Did you make sure you are in the fall 2017 semester?
Best, 
Melvin Wolf

**Comment by ruicao-github** [comment]
Dear Melvin Wolf,

yes, I am in Spring 2017 semester. But apparently I am not registered on the Jgrader.

Best,

Cao Rui
![capture](https://cloud.githubusercontent.com/assets/10601113/22901701/cf4b079e-f232-11e6-9448-29a86508ae32.PNG)

**Comment by florian-rabe** [comment]
You're right: Some people whose registrations were processed late were not synced to grader yet.

I've fixed that now.
