### ISSUE TITLE
Homework Submission

### ISSUE THREAD

**Issue by ypan0411** [florian-rabe/Teaching#28]
After the discussion, we made an agreement on how to submit the homework.

Please create a private repository by next Tuesday, and add @florian-rabe @aulon and me as collaborators. Also, please inform Florian the match of your real name and GitHub username.

Ps: as a student, you can create private repositories for free. You can get the student developer pack here: https://education.github.com/pack

**Comment by kylbar** [comment]
should we email him?

**Comment by florian-rabe** [comment]
I'll collect your user name-real name mappings next week in the lecture.
