### ISSUE TITLE
Small mistake in the notes

### ISSUE THREAD

**Issue by MelvinWolf** [florian-rabe/Teaching#31]
There seems to be a word missing between "mentioned" and "and programs" (see screenshot). 
I hope this helpfull and not nitpicking. 
![error cs](https://cloud.githubusercontent.com/assets/25617472/23132351/95ab1762-f78d-11e6-8f52-c6eae77bd76d.PNG)

**Comment by florian-rabe** [comment]
Thanks. It's fixed now.
