### ISSUE TITLE
Homework Submission 

### ISSUE THREAD

**Issue by orxh** [florian-rabe/Teaching#37]
- Some of you are submitting source files and PDFs to jgrader. Please submit only zip files.

- Make sure to submit all the files before the deadline. Grading late assignments sent by email is not possible.

**Comment by MelvinWolf** [comment]
I don't know if this is just me or everyone, but I cannot upload any homework 3 files on jgrader.
"Submit files
CH08-320201 Algorithms and Data Structures

No tasks are currently available!" 

I hope I didn't miss anything.

**Comment by ColinRothgang** [comment]
I have the same issue.

MelvinWolf:
