### ISSUE TITLE
Square-and-multiply algorithm on lecture notes (AaDS)

### ISSUE THREAD

**Issue by gcakir** [florian-rabe/Teaching#40]
![error sqmult](https://cloud.githubusercontent.com/assets/19774563/23333155/0ad933d2-fb87-11e6-9837-a746fb385bd5.png)

It seems that square-and-multiply algorithm on page 33 will not terminate. (Please go over it; I might have failed to notice that it could work.) I found the following implementation on Wikipedia ([Click here to view it](https://en.wikipedia.org/wiki/Exponentiation_by_squaring)) and it appears to be a good example of it.

```
Function exp_by_squaring(x, n)
    if n < 0  then return exp_by_squaring(1 / x, -n);
    else if n = 0  then return  1;
    else if n = 1  then return  x ;
    else if n is even  then return exp_by_squaring(x * x,  n / 2);
    else if n is odd  then return x * exp_by_squaring(x * x, (n - 1) / 2);
```

**Comment by orxh** [comment]
It does terminate with n=0.

**Comment by gcakir** [comment]
Thank you very much! Yes, you are right; it should terminate. My problem was that when implementing it in certain languages, such as Python 3, division of an odd number returns a floating point number and this causes problems, i.e. code not terminating.
