### ISSUE TITLE
Problem 3.1

### ISSUE THREAD

**Issue by florian-rabe** [florian-rabe/Teaching#42]
One student asks by email:

I had a question regarding the first problem of the 3rd homework in Algorithms 
and Data Structures.
One part of the problem is to argue informally why there can be no better 
algorithm. I am confused as to how does one do that.
I can only say that this is the algorithm that I came up with and that it takes 
the least amount of steps/operations possible. Could you give an example of 
correct solution to the problem?

**Comment by florian-rabe** [comment]
Generally such arguments are very difficult.
Therefore, I do not expect a rigorous proof.

However, sometimes we can give a convincing argument relatively easily.

For example, in the lecture we concluded that Theta(n^2) is optimal for adding n-dimensional square matrices.
Here the argument was that any correct algorithm has to produce a matrix with n^2 entries that are in general independent of each other.
Therefore, even the optimal algorithm must take Theta(n^2) steps.

For the 3 problems in the homeworks, it is possible to give similar arguments, with a little thinking.

**Comment by MelvinWolf** [comment]
How about 3.1.3 (the password one): Do we assume the password to be random?
Because (as you surely know) in real-life, some passwords (for example 1111111 or "password") are way more common than random sequences. My question is, can I ignore this while arguing why my algorithm is efficient?

**Comment by ColinRothgang** [comment]
You are supposed to compute the worst time complexity, right?

MelvinWolf:

**Comment by MelvinWolf** [comment]
Sorry, of course. 
All good.
