### ISSUE TITLE
AaDS: No slot for the third homework (HW #3)

### ISSUE THREAD

**Issue by gcakir** [florian-rabe/Teaching#46]
Hello,

I cannot upload my solutions for the third homework because no slot is created.

**Comment by Ar-Ghosh** [comment]
Me neither. Jgrader says "No tasks are currently available!"

**Comment by erdanielx** [comment]
I have this same issue

**Comment by latticepolys** [comment]
Me too! Hopefully it can be solved soon because I don't know when I'll wake up tomorrow.

**Comment by florian-rabe** [comment]
I've added the slots and extended the deadline until Friday morning.
