### ISSUE TITLE
Homeworks

### ISSUE THREAD

**Issue by florian-rabe** [florian-rabe/Teaching#49]
I've uploaded a partial solution to Subproblems 1-3 of question 2.1.

As discussed in the lecture, deadline HW 2+3 are pushed to the respective Tuesday.

I've also adapted the problem statement to make it a little simpler and fit the partial solution better.

As before, you can alternative implement it in a different language.

**Comment by funkytori** [comment]
I have a small request:
Could we get the final version of the homework when it is assigned?
Because the way things are, finishing early is not an option since we have to modify our homework every time the statement changes.

**Comment by florian-rabe** [comment]
Well, that's always the plan, and it usually works out.

But this time many students were confused and asked for an extension.
So I decided to simplify it.

Any solution to the original formulation version will of course be accepted as well.

**Comment by aaleryani** [comment]
I was surprised too when I opened the document to see some things have changed. I managed to incorporate the new changes, but I almost missed them.

**Comment by florian-rabe** [comment]
Sorry, I should have put a footnote in the pdf.

The change is not significant in the sense that the solutions that follow the overall spirit but deviate in the details also deserve full credit.
