### ISSUE TITLE
Grading

### ISSUE THREAD

**Issue by florian-rabe** [florian-rabe/Teaching#5]
The course will be graded as follows:
* 7 quizzes at 5 % each
* homeworks at 15 %
* 50 % final exam

bonus credit as announced

**Comment by latticepolys** [comment]
Dear Instructor, 
I wanted to know when the quizzes will occur and the homeworks will be posted because I had some immigration issue that's now solved and for this reason I am still not at the university. Although hopefully I will be very soon. Thanks! 
Jose Urriola

**Comment by florian-rabe** [comment]
I'll post the first homework this week.

There will be no quiz this week.
