### ISSUE TITLE
Typo in AaDS lecture notes

### ISSUE THREAD

**Issue by tkw1536** [florian-rabe/Teaching#53]
In Example 3.10 (https://github.com/florian-rabe/Teaching/blob/master/AaDS_17/goals.tex#L215) it should be ```it is sufficient to prove $\gcd(x,y)=\gcd(x, y-x)``` not ```it is sufficient to prove $\gcd(x,y)=\gcd(y-x)```. ```gcd``` on one argument makes no sense here.

**Comment by florian-rabe** [comment]
Thanks, fixed.
