### ISSUE TITLE
Quiz 3 without name on it

### ISSUE THREAD

**Issue by florian-rabe** [florian-rabe/Teaching#71]
I have a quiz without a name on it.

Please report if you took the quiz but don't have a grade in grader.

**Comment by mmshress** [comment]
Hi, I took the quiz but don't have a grade on it yet, it might be me. I'm Mohit Shrestha, matr. number 30000762

**Comment by florian-rabe** [comment]
I've assigned the quiz to you as no one else has claimed it.
