### ISSUE TITLE
Final exam

### ISSUE THREAD

**Issue by florian-rabe** [florian-rabe/Teaching#97]
As announced in the lecture, you are allowed to bring 5 sheets (10 pages) of DIN A4 paper filled with arbitrary notes to the exam.

The only requirement is that you personally wrote the notes.

**Comment by gcakir** [comment]
Dear Professor,

Does this apply to AaDS final exam as well?

**Comment by florian-rabe** [comment]
Not sure yet. We can talk about it.

**Comment by aulon** [comment]
Can the cheat sheet be typed, not written by hand?

**Comment by florian-rabe** [comment]
Yes.

But everybody must prepare their own sheet. If you copy-paste from each other, it will count like cheating.
